spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/chesscoach
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  profiles:
    active: local