spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/chesscoach
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: local
ollama:
  base-url: http://localhost:11434
  model: qwen2.5:0.5b
